controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    control_mode_handler:
      type: kuka_controllers/ControlModeHandler
    event_broadcaster:
      type: kuka_controllers/EventBroadcaster
    twist_controller:
      type: kuka_controllers/TwistController
    cartesian_pose_broadcaster:
      type: kuka_controllers/CartesianPoseBroadcaster