robot_manager:
  ros__parameters:
    control_mode: 7
    client_ip: "192.168.56.15"
    controller_ip: "192.168.56.16"
    joint_position_controller_name: "joint_trajectory_controller"
    impedance_controller_name: "joint_impedance_controller"
    torque_controller_name: "effort_controller"
# Control mode enums:
#  1 - joint position control
#  2 - joint impedance control
#  3 - joint velocity control (not supported yet)
#  4 - joint torque control
# ... others are not yet supported
    joint_velocity_controller_name: "diffbot_controller"
    cartesian_velocity_controller_name: "twist_controller"

#  CARTESIAN_VELOCITY_CONTROL = 7,