/controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_impedance_controller:
      type: kuka_controllers/JointImpedanceController
    effort_controller:
      type: effort_controllers/JointGroupPositionController
    diffbot_controller:
      type: diff_drive_controller/DiffDriveController
  
    configure_components_on_start: [""]
